Bootstrap: docker
From: library/ubuntu:latest
IncludeCmd: yes

%setup
    # Copy a file that can't be easily retrieved during install
    cp /gpfs/software/source/cudnn-8.0-linux-x64-v5.1.tgz $SINGULARITY_ROOTFS

%post
    # Make gpfs folder to hold mount
    mkdir /gpfs
    # Update packagelist, etc
    apt-get -y update && apt-get -y upgrade
    # Install some necessary tools
    apt-get install -y build-essential wget vim cmake python-dev python-pip
    # Fetch and install NVIDIA driver
    wget http://us.download.nvidia.com/XFree86/Linux-x86_64/375.26/NVIDIA-Linux-x86_64-375.26.run
    sh NVIDIA-Linux-x86_64-375.26.run -x
    mv NVIDIA-Linux-x86_64-375.26 /usr/local
    cd /usr/local/NVIDIA-Linux-x86_64-375.26
    # Make links
    ln -s libcuda.so.375.26 libcuda.so
    ln -s libEGL.so.375.26 libEGL.so
    ln -s libGLESv1_CM.so.375.26 libGLESv1_CM.so
    ln -s libGLESv2.so.375.26 libGLESv2.so
    ln -s libGL.so.375.26 libGL.so
    ln -s libglx.so.375.26 libglx.so
    ln -s libnvcuvid.so.375.26 libnvcuvid.so
    ln -s libnvidia-cfg.so.375.26 libnvidia-cfg.so
    ln -s libnvidia-compiler.so.375.26 libnvidia-compiler.so
    ln -s libnvidia-eglcore.so.375.26 libnvidia-eglcore.so
    ln -s libnvidia-encode.so.375.26 libnvidia-encode.so
    ln -s libnvidia-fbc.so.375.26 libnvidia-fbc.so
    ln -s libnvidia-glcore.so.375.26 libnvidia-glcore.so
    ln -s libnvidia-glsi.so.375.26 libnvidia-glsi.so
    ln -s libnvidia-gtk2.so.375.26 libnvidia-gtk2.so
    ln -s libnvidia-gtk3.so.375.26 libnvidia-gtk3.so
    ln -s libnvidia-ifr.so.375.26 libnvidia-ifr.so
    ln -s libnvidia-ml.so.375.26 libnvidia-ml.so
    ln -s libnvidia-ml.so.375.26 libnvidia-ml.so.1
    ln -s libnvidia-opencl.so.375.26 libnvidia-opencl.so
    ln -s libnvidia-tls.so.375.26 libnvidia-tls.so
    ln -s libnvidia-wfb.so.375.26 libnvidia-wfb.so
    ln -s libvdpau_nvidia.so.375.26 libvdpau_nvidia.so
    ln -s libvdpau.so.375.26 libvdpau.so
    ln -s libvdpau_trace.so.375.26 libvdpau_trace.so
    ln -s libcuda.so.375.26 libcuda.so.1
    # Install cuda and cudnn
    cd /root
    wget https://developer.nvidia.com/compute/cuda/8.0/Prod2/local_installers/cuda_8.0.61_375.26_linux-run
    sh cuda_8.0.61_375.26_linux-run --toolkit -silent
    tar xzvf /cudnn-8.0-linux-x64-v5.1.tgz -C /usr/local
    # Get and build gromacs
    wget ftp://ftp.gromacs.org/pub/gromacs/gromacs-5.1.2.tar.gz
    tar xzvf gromacs-5.1.2.tar.gz
    cd gromacs-5.1.2
    mkdir build && cd build
    cmake .. -DGMX_BUILD_OWN_FFTW=ON -DREGRESSIONTEST_DOWNLOAD=ON -DGMX_GPU=ON -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda
    make
    make check
    make install
